#! /usr/bin/python2
from __future__ import division

import sys
import math
import StringIO
# import re
import timeit

sys.stdin = StringIO.StringIO("4\ninternational\ncollegiate\nprogramming\ncontest\n")
# sys.stdin = StringIO.StringIO("1\naosidoaisdoiaosdioasdoiaosdioioeioiaoisdoasasjdiajsdajnzmvnzgueiruqowieoqetugsnkvnzmncqiwueiqurkfndfmafasdaoskodaksdokqowkdoqkowdkoqkwdoqkwodkqowdkoqkwdokqwodkqowkdoqwkdokqowdkoqwdoqkwodkqowdkqowkdoqkwodkqowdaosidoaisdoiaosdioasdoiaosdioioeioiaoisdoasasjdiajsdajnzmvnzgueiruqowieoqetugsnkvnzmncqiwueiqurkfndfmafasdaoskodaksdokqowkdoqkowdkoqkwdoqkwodkqowdkoqkwdokqwodkqowkdoqwkdokqowdkoqwdoqkwodkqowdkqowkdoqkwodkqowdaosidoaisdoiaosdioasdoiaosdioioeioiaoisdoasasjdiajsdajnzmvnzgueiruqowieoqetugsnkvnzmncqiwueiqurkfndfmafasdaoskodaksdokqowkdoqkowdkoqkwdoqkwodkqowdkoqkwdokqwodkqowkdoqwkdokqowdkoqwdoqkwodkqowdkqowkdoqkwodkqowdaosidoaisdoiaosdioasdoiaosdioioeioiaoisdoasasjdiajsdajnzmvnzgueiruqowieoqetugsnkvnzmncqiwueiqurkfndfmafasdaoskodaksdokqowkdoqkowdkoqkwdoqkwodkqowdkoqkwdokqwodkqowkdoqwkdokqowdkoqwdoqkwodkqowdkqowkdoqkwodkqowdaosidoaisdoiaosdioasdoiaosdioioeioiaoisdoasasjdiajsdajnzmvnzgueiruqowieoqetugsnkvnzmncqiwueiqurkfndfmafasdaoskodaksdokqowkdoqkowdkoqkwdoqkwodkqowdkoqkwdokqwodkqowkdoqwkdokqowdkoqwdoqkwodkqowdkqowkdoqkwodkqowdaosidoaisdoiaosdioasdoiaosdioioeioiaoisdoasasjdiajsdajnzmvnzgueiruqowieoqetugsnkvnzmncqiwueiqurkfndfmafasdaoskodaksdokqowkdoqkowdkoqkwdoqkwodkqowdkoqkwdokqwodkqowkdoqwkdokqowdkoqwdoqkwodkqowdkqowkdoqkwodkqowdaosidoaisdoiaosdioasdoiaosdioioeioiaoisdoasasjdiajsdajnzmvnzgueiruqowieoqetugsnkvnzmncqiwueiqurkfndfmafasdaoskodaksdokqowkdoqkowdkoqkwdoqkwodkqowdkoqkwdokqwodkqowkdoqwkdokqowdkoqwdoqkwodkqowdkqowkdoqkwodkqowdaosidoaisdoiaosdioasdoiaosdioioeioiaoisdoasasjdiajsdajnzmvnzgueiruqowieoqetugsnkvnzmncqiwueiqurkfndfmafasdaoskodaksdokqowkdoqkowdkoqkwdoqkwodkqowdkoqkwdokqwodkqowkdoqwkdokqowdkoqwdoqkwodkqowdkqowkdoqkwodkqowdaosidoaisdoiaosdioasdoiaosdioioeioiaoisdoasasjdiajsdajnzmvnzgueiruqowieoqetugsnkvnzmncqiwueiqurkfndfmafasdaoskodaksdokqowkdoqkowdkoqkwdoqkwodkqowdkoqkwdokqwodkqowkdoqwkdokqowdkoqwdoqkwodkqowdkqowkdoqkwodkqowdaosidoaisdoiaosdioasdoiaosdioioeioiaoisdoasasjdiajsdajnzmvnzgueiruqowieoqetugsnkvnzmncqiwueiqurkfndfmafasdaoskodaksdokqowkdoqkowdkoqkwdoqkwodkqowdkoqkwdokqwodkqowkdoqwkdokqowdkoqwdoqkwodkqowdkqowkdoqkwodkqowdaosidoaisdoiaosdioasdoiaosdioioeioiaoisdoasasjdiajsdajnzmvnzgueiruqowieoqetugsnkvnzmncqiwueiqurkfndfmafasdaoskodaksdokqowkdoqkowdkoqkwdoqkwodkqowdkoqkwdokqwodkqowkdoqwkdokqowdkoqwdoqkwodkqowdkqowkdoqkwodkqowdaosidoaisdoiaosdioasdoiaosdioioeioiaoisdoasasjdiajsdajnzmvnzgueiruqowieoqetugsnkvnzmncqiwueiqurkfndfmafasdaoskodaksdokqowkdoqkowdkoqkwdoqkwodkqowdkoqkwdokqwodkqowkdoqwkdokqowdkoqwdoqkwodkqowdkqowkdoqkwodkqowdaosidoaisdoiaosdioasdoiaosdioioeioiaoisdoasasjdiajsdajnzmvnzgueiruqowieoqetugsnkvnzmncqiwueiqurkfndfmafasdaoskodaksdokqowkdoqkowdkoqkwdoqkwodkqowdkoqkwdokqwodkqowkdoqwkdokqowdkoqwdoqkwodkqowdkqowkdoqkwodkqowdaosidoaisdoiaosdioasdoiaosdioioeioiaoisdoasasjdiajsdajnzmvnzgueiruqowieoqetugsnkvnzmncqiwueiqurkfndfmafasdaoskodaksdokqowkdoqkowdkoqkwdoqkwodkqowdkoqkwdokqwodkqowkdoqwkdokqowdkoqwdoqkwodkqowdkqowkdoqkwodkqowdaosidoaisdoiaosdioasdoiaosdioioeioiaoisdoasasjdiajsdajnzmvnzgueiruqowieoqetugsnkvnzmncqiwueiqurkfndfmafasdaoskodaksdokqowkdoqkowdkoqkwdoqkwodkqowdkoqkwdokqwodkqowkdoqwkdokqowdkoqwdoqkwodkqowdkqowkdoqkwodkqowdaosidoaisdoiaosdioasdoiaosdioioeioiaoisdoasasjdiajsdajnzmvnzgueiruqowieoqetugsnkvnzmncqiwueiqurkfndfmafasdaoskodaksdokqowkdoqkowdkoqkwdoqkwodkqowdkoqkwdokqwodkqowkdoqwkdokqowdkoqwdoqkwodkqowdkqowkdoqkwodkqowdaosidoaisdoiaosdioasdoiaosdioioeioiaoisdoasasjdiajsdajnzmvnzgueiruqowieoqetugsnkvnzmncqiwueiqurkfndfmafasdaoskodaksdokqowkdoqkowdkoqkwdoqkwodkqowdkoqkwdokqwodkqowkdoqwkdokqowdkoqwdoqkwodkqowdkqowkdoqkwodkqowdaosidoaisdoiaosdioasdoiaosdioioeioiaoisdoasasjdiajsdajnzmvnzgueiruqowieoqetugsnkvnzmncqiwueiqurkfndfmafasdaoskodaksdokqowkdoqkowdkoqkwdoqkwodkqowdkoqkwdokqwodkqowkdoqwkdokqowdkoqwdoqkwodkqowdkqowkdoqkwodkqowdaosidoaisdoiaosdioasdoiaosdioioeioiaoisdoasasjdiajsdajnzmvnzgueiruqowieoqetugsnkvnzmncqiwueiqurkfndfmafasdaoskodaksdokqowkdoqkowdkoqkwdoqkwodkqowdkoqkwdokqwodkqowkdoqwkdokqowdkoqwdoqkwodkqowdkqowkdoqkwodkqowdaosidoaisdoiaosdioasdoiaosdioioeioiaoisdoasasjdiajsdajnzmvnzgueiruqowieoqetugsnkvnzmncqiwueiqurkfndfmafasdaoskodaksdokqowkdoqkowdkoqkwdoqkwodkqowdkoqkwdokqwodkqowkdoqwkdokqowdkoqwdoqkwodkqowdkqowkdoqkwodkqowdaosidoaisdoiaosdioasdoiaosdioioeioiaoisdoasasjdiajsdajnzmvnzgueiruqowieoqetugsnkvnzmncqiwueiqurkfndfmafasdaoskodaksdokqowkdoqkowdkoqkwdoqkwodkqowdkoqkwdokqwodkqowkdoqwkdokqowdkoqwdoqkwodkqowdkqowkdoqkwodkqowdaosidoaisdoiaosdioasdoiaosdioioeioiaoisdoasasjdiajsdajnzmvnzgueiruqowieoqetugsnkvnzmncqiwueiqurkfndfmafasdaoskodaksdokqowkdoqkowdkoqkwdoqkwodkqowdkoqkwdokqwodkqowkdoqwkdokqowdkoqwdoqkwodkqowdkqowkdoqkwodkqowdaosidoaisdoiaosdioasdoiaosdioioeioiaoisdoasasjdiajsdajnzmvnzgueiruqowieoqetugsnkvnzmncqiwueiqurkfndfmafasdaoskodaksdokqowkdoqkowdkoqkwdoqkwodkqowdkoqkwdokqwodkqowkdoqwkdokqowdkoqwdoqkwodkqowdkqowkdoqkwodkqowdaosidoaisdoiaosdioasdoiaosdioioeioiaoisdoasasjdiajsdajnzmvnzgueiruqowieoqetugsnkvnzmncqiwueiqurkfndfmafasdaoskodaksdokqowkdoqkowdkoqkwdoqkwodkqowdkoqkwdokqwodkqowkdoqwkdokqowdkoqwdoqkwodkqowdkqowkdoqkwodkqowdaosidoaisdoiaosdioasdoiaosdioioeioiaoisdoasasjdiajsdajnzmvnzgueiruqowieoqetugsnkvnzmncqiwueiqurkfndfmafasdaoskodaksdokqowkdoqkowdkoqkwdoqkwodkqowdkoqkwdokqwodkqowkdoqwkdokqowdkoqwdoqkwodkqowdkqowkdoqkwodkqowdaosidoaisdoiaosdioasdoiaosdioioeioiaoisdoasasjdiajsdajnzmvnzgueiruqowieoqetugsnkvnzmncqiwueiqurkfndfmafasdaoskodaksdokqowkdoqkowdkoqkwdoqkwodkqowdkoqkwdokqwodkqowkdoqwkdokqowdkoqwdoqkwodkqowdkqowkdoqkwodkqowdaosidoaisdoiaosdioasdoiaosdioioeioiaoisdoasasjdiajsdajnzmvnzgueiruqowieoqetugsnkvnzmncqiwueiqurkfndfmafasdaoskodaksdokqowkdoqkowdkoqkwdoqkwodkqowdkoqkwdokqwodkqowkdoqwkdokqowdkoqwdoqkwodkqowdkqowkdoqkwodkqowdaosidoaisdoiaosdioasdoiaosdioioeioiaoisdoasasjdiajsdajnzmvnzgueiruqowieoqetugsnkvnzmncqiwueiqurkfndfmafasdaoskodaksdokqowkdoqkowdkoqkwdoqkwodkqowdkoqkwdokqwodkqowkdoqwkdokqowdkoqwdoqkwodkqowdkqowkdoqkwodkqowdaosidoaisdoiaosdioasdoiaosdioioeioiaoisdoasasjdiajsdajnzmvnzgueiruqowieoqetugsnkvnzmncqiwueiqurkfndfmafasdaoskodaksdokqowkdoqkowdkoqkwdoqkwodkqowdkoqkwdokqwodkqowkdoqwkdokqowdkoqwdoqkwodkqowdkqowkdoqkwodkqowdaosidoaisdoiaosdioasdoiaosdioioeioiaoisdoasasjdiajsdajnzmvnzgueiruqowieoqetugsnkvnzmncqiwueiqurkfndfmafasdaoskodaksdokqowkdoqkowdkoqkwdoqkwodkqowdkoqkwdokqwodkqowkdoqwkdokqowdkoqwdoqkwodkqowdkqowkdoqkwodkqowdaosidoaisdoiaosdioasdoiaosdioioeioiaoisdoasasjdiajsdajnzmvnzgueiruqowieoqetugsnkvnzmncqiwueiqurkfndfmafasdaoskodaksdokqowkdoqkowdkoqkwdoqkwodkqowdkoqkwdokqwodkqowkdoqwkdokqowdkoqwdoqkwodkqowdkqowkdoqkwodkqowdaosidoaisdoiaosdioasdoiaosdioioeioiaoisdoasasjdiajsdajnzmvnzgueiruqowieoqetugsnkvnzmncqiwueiqurkfndfmafasdaoskodaksdokqowkdoqkowdkoqkwdoqkwodkqowdkoqkwdokqwodkqowkdoqwkdokqowdkoqwdoqkwodkqowdkqowkdoqkwodkqowdaosidoaisdoiaosdioasdoiaosdioioeioiaoisdoasasjdiajsdajnzmvnzgueiruqowieoqetugsnkvnzmncqiwueiqurkfndfmafasdaoskodaksdokqowkdoqkowdkoqkwdoqkwodkqowdkoqkwdokqwodkqowkdoqwkdokqowdkoqwdoqkwodkqowdkqowkdoqkwodkqowdaosidoaisdoiaosdioasdoiaosdioioeioiaoisdoasasjdiajsdajnzmvnzgueiruqowieoqetugsnkvnzmncqiwueiqurkfndfmafasdaoskodaksdokqowkdoqkowdkoqkwdoqkwodkqowdkoqkwdokqwodkqowkdoqwkdokqowdkoqwdoqkwodkqowdkqowkdoqkwodkqowdaosidoaisdoiaosdioasdoiaosdioioeioiaoisdoasasjdiajsdajnzmvnzgueiruqowieoqetugsnkvnzmncqiwueiqurkfndfmafasdaoskodaksdokqowkdoqkowdkoqkwdoqkwodkqowdkoqkwdokqwodkqowkdoqwkdokqowdkoqwdoqkwodkqowdkqowkdoqkwodkqowdaosidoaisdoiaosdioasdoiaosdioioeioiaoisdoasasjdiajsdajnzmvnzgueiruqowieoqetugsnkvnzmncqiwueiqurkfndfmafasdaoskodaksdokqowkdoqkowdkoqkwdoqkwodkqowdkoqkwdokqwodkqowkdoqwkdokqowdkoqwdoqkwodkqowdkqowkdoqkwodkqowdaosidoaisdoiaosdioasdoiaosdioioeioiaoisdoasasjdiajsdajnzmvnzgueiruqowieoqetugsnkvnzmncqiwueiqurkfndfmafasdaoskodaksdokqowkdoqkowdkoqkwdoqkwodkqowdkoqkwdokqwodkqowkdoqwkdokqowdkoqwdoqkwodkqowdkqowkdoqkwodkqowdaosidoaisdoiaosdioasdoiaosdioioeioiaoisdoasasjdiajsdajnzmvnzgueiruqowieoqetugsnkvnzmncqiwueiqurkfndfmafasdaoskodaksdokqowkdoqkowdkoqkwdoqkwodkqowdkoqkwdokqwodkqowkdoqwkdokqowdkoqwdoqkwodkqowdkqowkdoqkwodkqowdaosidoaisdoiaosdioasdoiaosdioioeioiaoisdoasasjdiajsdajnzmvnzgueiruqowieoqetugsnkvnzmncqiwueiqurkfndfmafasdaoskodaksdokqowkdoqkowdkoqkwdoqkwodkqowdkoqkwdokqwodkqowkdoqwkdokqowdkoqwdoqkwodkqowdkqowkdoqkwodkqowdaosidoaisdoiaosdioasdoiaosdioioeioiaoisdoasasjdiajsdajnzmvnzgueiruqowieoqetugsnkvnzmncqiwueiqurkfndfmafasdaoskodaksdokqowkdoqkowdkoqkwdoqkwodkqowdkoqkwdokqwodkqowkdoqwkdokqowdkoqwdoqkwodkqowdkqowkdoqkwodkqowdaosidoaisdoiaosdioasdoiaosdioioeioiaoisdoasasjdiajsdajnzmvnzgueiruqowieoqetugsnkvnzmncqiwueiqurkfndfmafasdaoskodaksdokqowkdoqkowdkoqkwdoqkwodkqowdkoqkwdokqwodkqowkdoqwkdokqowdkoqwdoqkwodkqowdkqowkdoqkwodkqowdaosidoaisdoiaosdioasdoiaosdioioeioiaoisdoasasjdiajsdajnzmvnzgueiruqowieoqetugsnkvnzmncqiwueiqurkfndfmafasdaoskodaksdokqowkdoqkowdkoqkwdoqkwodkqowdkoqkwdokqwodkqowkdoqwkdokqowdkoqwdoqkwodkqowdkqowkdoqkwodkqowdaosidoaisdoiaosdioasdoiaosdioioeioiaoisdoasasjdiajsdajnzmvnzgueiruqowieoqetugsnkvnzmncqiwueiqurkfndfmafasdaoskodaksdokqowkdoqkowdkoqkwdoqkwodkqowdkoqkwdokqwodkqowkdoqwkdokqowdkoqwdoqkwodkqowdkqowkdoqkwodkqowdaosidoaisdoiaosdioasdoiaosdioioeioiaoisdoasasjdiajsdajnzmvnzgueiruqowieoqetugsnkvnzmncqiwueiqurkfndfmafasdaoskodaksdokqowkdoqkowdkoqkwdoqkwodkqowdkoqkwdokqwodkqowkdoqwkdokqowdkoqwdoqkwodkqowdkqowkdoqkwodkqowdaosidoaisdoiaosdioasdoiaosdioioeioiaoisdoasasjdiajsdajnzmvnzgueiruqowieoqetugsnkvnzmncqiwueiqurkfndfmafasdaoskodaksdokqowkdoqkowdkoqkwdoqkwodkqowdkoqkwdokqwodkqowkdoqwkdokqowdkoqwdoqkwodkqowdkqowkdoqkwodkqowdaosidoaisdoiaosdioasdoiaosdioioeioiaoisdoasasjdiajsdajnzmvnzgueiruqowieoqetugsnkvnzmncqiwueiqurkfndfmafasdaoskodaksdokqowkdoqkowdkoqkwdoqkwodkqowdkoqkwdokqwodkqowkdoqwkdokqowdkoqwdoqkwodkqowdkqowkdoqkwodkqowdaosidoaisdoiaosdioasdoiaosdioioeioiaoisdoasasjdiajsdajnzmvnzgueiruqowieoqetugsnkvnzmncqiwueiqurkfndfmafasdaoskodaksdokqowkdoqkowdkoqkwdoqkwodkqowdkoqkwdokqwodkqowkdoqwkdokqowdkoqwdoqkwodkqowdkqowkdoqkwodkqowdaosidoaisdoiaosdioasdoiaosdioioeioiaoisdoasasjdiajsdajnzmvnzgueiruqowieoqetugsnkvnzmncqiwueiqurkfndfmafasdaoskodaksdokqowkdoqkowdkoqkwdoqkwodkqowdkoqkwdokqwodkqowkdoqwkdokqowdkoqwdoqkwodkqowdkqowkdoqkwodkqowdaosidoaisdoiaosdioasdoiaosdioioeioiaoisdoasasjdiajsdajnzmvnzgueiruqowieoqetugsnkvnzmncqiwueiqurkfndfmafasdaoskodaksdokqowkdoqkowdkoqkwdoqkwodkqowdkoqkwdokqwodkqowkdoqwkdokqowdkoqwdoqkwodkqowdkqowkdoqkwodkqowdaosidoaisdoiaosdioasdoiaosdioioeioiaoisdoasasjdiajsdajnzmvnzgueiruqowieoqetugsnkvnzmncqiwueiqurkfndfmafasdaoskodaksdokqowkdoqkowdkoqkwdoqkwodkqowdkoqkwdokqwodkqowkdoqwkdokqowdkoqwdoqkwodkqowdkqowkdoqkwodkqowd\ncollegiate\nprogramming\ncontest\n")
start = timeit.default_timer()
elements = "H,He,Li,Be,B,C,N,O,F,Ne,Na,Mg,Al,Si,P,S,Cl,Ar,K,Ca,Sc,Ti,V,Cr,Mn,Fe,Co,Ni,Cu,Zn,Ga,Ge,As,Se,Br,Kr,Rb,Sr,Y,Zr,Nb,Mo,Tc,Ru,Rh,Pd,Ag,Cd,In,Sn,Sb,Te,I,Xe,Cs,Ba,Hf,Ta,W,Re,Os,Ir,Pt,Au,Hg,Tl,Pb,Bi,Po,At,Rn,Fr,Ra,Rf,Db,Sg,Bh,Hs,Mt,Ds,Rg,Cn,Fl,Lv,La,Ce,Pr,Nd,Pm,Sm,Eu,Gd,Tb,Dy,Ho,Er,Tm,Yb,Lu,Ac,Th,Pa,U,Np,Pu,Am,Cm,Bk,Cf,Es,Fm,Md,No,Lr"
elementsList = elements.lower().split(',')
def main():
	num = sys.stdin.readline()
	num = int(num)
	for i in range(num):
		string = sys.stdin.readline().replace('\n','').lower()
		ones = [False]*len(string)
		twos = [False]*len(string)
		for i in  range(len(string))[::-1]:
			orOnes = False
			if i<len(string)-1:
				orOnes = ones[i+1] or twos[i+1]


			if string[i:i+1] in elementsList\
				and (i<len(string)-1 and orOnes or  i == len(string)-1):
				ones[i] = True
			orTwos = False
			if i < len(string)-2:
				orTwos = ones[i+2] or twos[i+2]
			if string[i:i+2] in elementsList and i < len(string)-1\
				and (i<len(string)-2 and orTwos or  i ==len(string)-2):
				twos[i] = True

		if ones[0] or twos[0]:
			print "YES"
		else:
			print "NO"

def dfs(string):
	if len(string)==0:
		return True
	else:
		one=string[:1]
		two=string[:2]
		oneIn =  one in elementsList 
		twoIn =  two in elementsList 
		if oneIn and twoIn:
			return dfs(string[1:]) or dfs(string[2:])
		elif oneIn and not twoIn:
			return dfs(string[1:]) 
		elif not oneIn and twoIn:
			return dfs(string[2:])
		else:
			return False

main()
stop = timeit.default_timer()

print stop - start 
	